fix(test): update playwright docker image
This fixes the error seen in CI:

Error: browserType.launch: Executable doesn't exist at /ms-playwright/firefox-1538/firefox/firefox
    ╔════════════════════════════════════════════════════════╗
    ║ Looks like Playwright was just updated to 1.62.0.      ║
    ║ Please update docker image as well.                    ║
    ║ -  current: mcr.microsoft.com/playwright:v1.61.0-noble ║
    ║ - required: mcr.microsoft.com/playwright:v1.62.0-noble ║
    ║                                                        ║
    ║ <3 Playwright Team                                     ║
    ╚════════════════════════════════════════════════════════╝